### PR TITLE
Added component data to bug info popup

### PR DESCRIPTION
**Pull request by jaredpetersen**
Added component data to the popup that displays when the user hovers over bug as discussed in Issue #67.

This request differs from closed pull request #129, as it displays component data regardless of the number of days that have passed since the bug has been updated.

### CODE REVIEW

**Comment by jdm** [comment]
Looking good! Could you make this work for github issues too, by setting the component property in https://github.com/jaredpetersen/bugsahoy/blob/90b54a8a2256d4cf846a760dffd2d70a0b36f582/magic.js#L549 ? We can probably just display the repository name for it.

**Comment by jaredpetersen** [comment]
Yes, I can! I'll work on implementing this in a few hours.

**Comment by jaredpetersen** [comment]
Good to go!

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
