### PR TITLE
Add Diamond Bugs

### PR DESCRIPTION
**Pull request by jaredpetersen**
Added diamond bugs and diamond bug highlighting. Let me know if you would like to use a different color. Fixes Issue #94.

### CODE REVIEW

**Comment by jdm** [comment]
Ooh, I like that! Good choice on the highlighting!

**Comment by jdm** [comment]
Sorry, I had to revert these changes because they broke searching Github repositories. You can use the `Servo` category as a good testcase.

**Comment by jaredpetersen** [comment]
Hmmm... Sorry about that. I'll look into it as soon as I can.

**Comment by jaredpetersen** [comment]
I'm testing a fork with the diamond bugs added back in, and I'm not seeing searches on GitHub repositories breaking. What was the exact symptopm?

Here are my test cases:

Test 1 -> "Servo" Checked
Expected result: Only servo bugs appear
Actual result: Only servo bugs appear

Test 2 -> "Servo" and "Diamond Bugs" Checked
Expected result: No bugs shown, GitHub doesn't have diamond bugs
Actual result: No bugs shown, GitHub doesn't have diamond bugs

Test 3 -> "Diamond Bugs" Checked
Expected result: Only diamond bugs shown
Actual result: Only diamond bugs are shown

You can check out the fork here https://github.com/jaredpetersen/bugsahoy.

**Comment by jdm** [comment]
It was the highlighting that hit the problem: https://github.com/jdm/bugsahoy/commit/f7c55425f50051921f450d1a33971df4b467f5dc . The webconsole shows "bug.whiteboard is undefined" and no github results are retrieved.

**Comment by jaredpetersen** [comment]
@jdm That was super helpful! I didn't implement highlighting in the fork at that point, so I wasn't seeing the problem. I've created a new pull request (#136) to reimplement diamond bugs and fix diamond bug highlighting.

**Pull request merged**
